apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cidr-calculator-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "cidr-calculator-ip"
    networking.gke.io/managed-certificates: "cidr-calculator-cert"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: cidr-calculator-service
            port:
              number: 80
