apiVersion: v1
kind: Service
metadata:
  name: cidr-calculator-service
  labels:
    app: cidr-calculator
spec:
  type: NodePort
  selector:
    app: cidr-calculator
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
